import {apiFetch,connectPages} from './api.js';
import {rpc} from './rpc.js';import {formatTime,parseTime,moveRange} from './timeline.mjs';
const $=id=>document.getElementById(id);let youtubePlayer=null,objectUrl=null,player=null,meta=null,apiPromise=null,rangePlaying=false,loading=false,revision=0;
function error(text){$('video-error').textContent=text;}
function api(){if(window.YT?.Player)return Promise.resolve();if(!apiPromise)apiPromise=new Promise((resolve,reject)=>{window.onYouTubeIframeAPIReady=resolve;const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>reject(Error('YouTube 플레이어를 불러올 수 없습니다.'));document.head.append(s);});return apiPromise;}
function values(){return {start:Number($('start').value),end:Number($('end').value)};}
function draw(){if(!meta)return;const {start,end}=values();$('selection').style.left=start/meta.duration*100+'%';$('selection').style.width=(end-start)/meta.duration*100+'%';for(const [kind,v]of [['start',start],['end',end]]){const handle=$(kind+'-handle');handle.style.left=v/meta.duration*100+'%';handle.setAttribute('aria-valuenow',v);handle.setAttribute('aria-valuemax',meta.duration);handle.setAttribute('aria-valuetext',formatTime(v));$(kind+'-time').value=formatTime(v);}document.dispatchEvent(new Event('rangechange'));}
function move(kind,value){if(!meta)return;const old=values(),{start,end}=moveRange(old.start,old.end,meta.duration,kind,value);$('start').value=start;$('end').value=end;rangePlaying=false;draw();document.dispatchEvent(new Event('input'));}
for(const kind of ['start','end']){const handle=$(kind+'-handle');handle.addEventListener('pointerdown',e=>{if(!meta)return;e.preventDefault();handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointermove',e=>{if(!meta||!handle.hasPointerCapture(e.pointerId))return;const r=$('timeline').getBoundingClientRect();move(kind,(e.clientX-r.left)/r.width*meta.duration);});handle.addEventListener('keydown',e=>{const delta=e.shiftKey?10:1;let n=Number($(kind).value);if(['ArrowLeft','ArrowDown'].includes(e.key))n-=delta;else if(['ArrowRight','ArrowUp'].includes(e.key))n+=delta;else if(e.key==='Home')n=0;else if(e.key==='End')n=meta?.duration??0;else return;e.preventDefault();move(kind,n);});$(kind+'-time').addEventListener('change',()=>{try{move(kind,parseTime($(kind+'-time').value));error('');}catch(e){error(e.message);draw();}});$('mark-'+kind).addEventListener('click',()=>move(kind,player?.getCurrentTime()??0));}
let clipPreview=null;
function invalidate(){clipPreview?.remove();clipPreview=null;document.getElementById('youtube-player').hidden=false;for(const k of ['start','end'])$('mark-'+k).disabled=false;revision++;$('video-panel').dataset.uploadId='';$('file-preview').pause();$('file-preview').hidden=true;meta=null;rangePlaying=false;player?.pauseVideo?.();$('video-panel').dataset.ready='false';$('video-panel').dataset.open='false';$('timeline-panel').hidden=true;$('video-preview').hidden=true;document.dispatchEvent(new Event('videoready'));}
$('video-url').addEventListener('input',invalidate);
$('load-video').addEventListener('click',async()=>{if(loading)return;loading=true;$('load-video').disabled=true;invalidate();const rev=revision,url=$('video-url').value;error('');try{const info=await rpc('video-info',{url});if(info.provider!=='chzzk')await api();if(rev!==revision)return;meta=info;$('video-title').textContent=info.title+' · '+formatTime(info.duration);$('cinema-admission').textContent=info.admission.open?'오늘은 영상 신청을 받고 있어요.':'현재는 영상 신청을 받지 않습니다.';$('video-panel').dataset.open=String(info.admission.open);$('start').value=0;$('end').value=Math.min(info.duration,30);$('timeline-panel').hidden=false;$('video-preview').hidden=false;draw();
 const ready=()=>{if(rev!==revision)return;$('video-panel').dataset.ready='true';document.dispatchEvent(new Event('videoready'));};
 if(info.provider==='chzzk'){
 youtubePlayer?.pauseVideo?.();document.getElementById('youtube-player').hidden=true;for(const k of ['start','end'])$('mark-'+k).disabled=true;
 const showClip=(autoplay=false,startSeconds=0,endSeconds=info.duration)=>{clipPreview?.remove();clipPreview=document.createElement('iframe');clipPreview.title='치지직 클립 미리보기';clipPreview.allow='autoplay; fullscreen';clipPreview.style.cssText='width:100%;height:300px;border:0';clipPreview.src='https://chzzk.naver.com/embed/clip/'+info.clipId+'?autoplay='+Number(autoplay)+'&start='+startSeconds+'&end='+endSeconds;clipPreview.referrerPolicy='strict-origin-when-cross-origin';$('video-preview').append(clipPreview);};
 showClip();player={pauseVideo:()=>{clipPreview?.remove();clipPreview=null;},loadVideoById:({startSeconds,endSeconds})=>showClip(true,startSeconds,endSeconds)};ready();
 error('치지직 클립은 시작·종료 시간을 직접 지정해 주세요. 현재 재생 위치 가져오기는 지원하지 않습니다.');
 }else if(youtubePlayer){player=youtubePlayer;player.cueVideoById(info.videoId);ready();}else player=youtubePlayer=new YT.Player('youtube-player',{width:'100%',height:'100%',videoId:info.videoId,playerVars:{origin:location.origin,playsinline:1},events:{onReady:ready,onAutoplayBlocked:()=>error('플레이어의 재생 버튼을 눌러 주세요.'),onError:e=>{const messages={2:'잘못된 영상 주소입니다.',5:'브라우저에서 이 영상을 재생할 수 없습니다.',100:'삭제되었거나 비공개 영상입니다.',101:'이 영상은 외부 사이트 재생을 허용하지 않습니다.',150:'이 영상은 외부 사이트 재생을 허용하지 않습니다.',153:'YouTube가 사이트 식별 정보를 확인하지 못했습니다.'};error(messages[e.data]||`YouTube 재생 오류 (${e.data})`);$('video-panel').dataset.ready='false';document.dispatchEvent(new Event('videoready'));}}});
 }catch(e){error(e.message);}finally{loading=false;$('load-video').disabled=false;}});
$('preview-range').addEventListener('click',()=>{if(!player||!meta)return;const {start,end}=values();rangePlaying=true;player.loadVideoById({videoId:meta.videoId,startSeconds:start,endSeconds:end});});
document.addEventListener('modechange',()=>{if($('video-panel').hidden){player?.pauseVideo?.();rangePlaying=false;}});
setInterval(()=>{if(!meta||!player?.getCurrentTime||document.hidden||$('video-panel').hidden)return;const t=player.getCurrentTime();$('playhead-time').textContent='현재 '+formatTime(t);$('playhead').style.left=Math.min(100,t/meta.duration*100)+'%';if(rangePlaying&&t>=Number($('end').value)){player.pauseVideo();rangePlaying=false;}},250);

$('video-file').addEventListener('change',async()=>{
 const file=$('video-file').files?.[0];if(!file||loading)return;invalidate();const rev=revision;loading=true;$('load-video').disabled=true;$('video-file').disabled=true;
 try{if(file.size>50*1024*1024||!['video/mp4','video/webm'].includes(file.type))throw Error('MP4 또는 WebM 파일을 50MB 이하로 선택해 주세요.');
 $('upload-status').textContent='업로드 준비 중…';const ticket=await rpc('upload-ticket',{name:file.name,size:file.size,mime:file.type});
 $('upload-status').textContent='영상 전송 중…';const sent=await apiFetch('/api/viewer/upload?job='+encodeURIComponent(ticket.jobId),{method:'POST',body:file});if(!sent.ok)throw Error((await sent.json()).error||'업로드 실패');
 $('upload-status').textContent='방송 서버에서 영상 검사 중…';const info=await rpc('upload-finish',{mediaId:ticket.upload.mediaId});if(rev!==revision)return;
 meta=info;$('video-panel').dataset.uploadId=info.uploadId;$('video-panel').dataset.open=String(info.admission.open);$('cinema-admission').textContent=info.admission.open?'오늘은 영상 신청을 받고 있어요.':'현재는 영상 신청을 받지 않습니다.';
 if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);const media=$('file-preview');media.src=objectUrl;media.hidden=false;youtubePlayer?.pauseVideo?.();
 player={getCurrentTime:()=>media.currentTime,pauseVideo:()=>media.pause(),loadVideoById:({startSeconds})=>{media.currentTime=startSeconds;media.play().catch(()=>error('영상의 재생 버튼을 눌러 주세요.'));}};
 $('start').value=0;$('end').value=Math.min(30,info.duration);$('video-title').textContent=info.title+' · '+formatTime(info.duration);$('timeline-panel').hidden=false;$('video-panel').dataset.ready='true';draw();document.dispatchEvent(new Event('videoready'));$('upload-status').textContent='업로드 완료 · 원하는 구간을 골라 신청해 주세요. 파일은 임시 보관됩니다.';
 }catch(e){$('upload-status').textContent=e.message;}finally{loading=false;$('load-video').disabled=false;$('video-file').disabled=false;}
});
